/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsWhyGenGenRouteImport } from './routes/docs.why-gen-gen'
import { Route as DocsVitePluginRouteImport } from './routes/docs.vite-plugin'
import { Route as DocsUsingGeneratorsRouteImport } from './routes/docs.using-generators'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsApiRouteImport } from './routes/docs.api'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWhyGenGenRoute = DocsWhyGenGenRouteImport.update({
  id: '/why-gen-gen',
  path: '/why-gen-gen',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVitePluginRoute = DocsVitePluginRouteImport.update({
  id: '/vite-plugin',
  path: '/vite-plugin',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUsingGeneratorsRoute = DocsUsingGeneratorsRouteImport.update({
  id: '/using-generators',
  path: '/using-generators',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/using-generators': typeof DocsUsingGeneratorsRoute
  '/docs/vite-plugin': typeof DocsVitePluginRoute
  '/docs/why-gen-gen': typeof DocsWhyGenGenRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/using-generators': typeof DocsUsingGeneratorsRoute
  '/docs/vite-plugin': typeof DocsVitePluginRoute
  '/docs/why-gen-gen': typeof DocsWhyGenGenRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/using-generators': typeof DocsUsingGeneratorsRoute
  '/docs/vite-plugin': typeof DocsVitePluginRoute
  '/docs/why-gen-gen': typeof DocsWhyGenGenRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/api'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/troubleshooting'
    | '/docs/using-generators'
    | '/docs/vite-plugin'
    | '/docs/why-gen-gen'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/docs/api'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/troubleshooting'
    | '/docs/using-generators'
    | '/docs/vite-plugin'
    | '/docs/why-gen-gen'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/api'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/troubleshooting'
    | '/docs/using-generators'
    | '/docs/vite-plugin'
    | '/docs/why-gen-gen'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/why-gen-gen': {
      id: '/docs/why-gen-gen'
      path: '/why-gen-gen'
      fullPath: '/docs/why-gen-gen'
      preLoaderRoute: typeof DocsWhyGenGenRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/vite-plugin': {
      id: '/docs/vite-plugin'
      path: '/vite-plugin'
      fullPath: '/docs/vite-plugin'
      preLoaderRoute: typeof DocsVitePluginRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/using-generators': {
      id: '/docs/using-generators'
      path: '/using-generators'
      fullPath: '/docs/using-generators'
      preLoaderRoute: typeof DocsUsingGeneratorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsUsingGeneratorsRoute: typeof DocsUsingGeneratorsRoute
  DocsVitePluginRoute: typeof DocsVitePluginRoute
  DocsWhyGenGenRoute: typeof DocsWhyGenGenRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsCliRoute: DocsCliRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsUsingGeneratorsRoute: DocsUsingGeneratorsRoute,
  DocsVitePluginRoute: DocsVitePluginRoute,
  DocsWhyGenGenRoute: DocsWhyGenGenRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
